baseURL = "https://serenewalks.github.io/"
title = "Serene Walks"
languageCode = "ko"
paginate = 10
theme = "PaperMod"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
