baseURL = "https://serenewalks.github.io/"
title = "Serene Walks"
languageCode = "ko"
paginate = 10

# PaperMod 테마를 명시!
theme = "PaperMod"

# Hugo Modules로 PaperMod를 자동으로 가져오기
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
